In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [ ]:
#printing csv files
df1=pd.read_csv(r'/content/state_wise_crop_production.csv')
print(df1.head())
df2=pd.read_csv(r'/content/crop_production (1).csv')
print(df2.head())
df3=pd.read_csv(r'/content/cpdata.csv')
print(df3.head())
df4=pd.read_csv(r'/content/cropproductiononvariousfactors.csv')
print(df4.head())
df5=pd.read_csv(r'/content/cropph.csv')
print(df5.head())
print("null values in df1",df1.isnull().sum())
print("null values in df2",df2.isnull().sum())
print("null values in df3",df3.isnull().sum())
print("null values in df4",df4.isnull().sum())
print("null values in df5",df5.isnull().sum())

    Crop           State  Cost of Cultivation (`/Hectare) A2+FL  \
0  ARHAR   Uttar Pradesh                                9794.05
1  ARHAR       Karnataka                               10593.15
2  ARHAR         Gujarat                               13468.82
3  ARHAR  Andhra Pradesh                               17051.66
4  ARHAR     Maharashtra                               17130.55

   Cost of Cultivation (`/Hectare) C2  Cost of Production (`/Quintal) C2  \
0                            23076.74                            1941.55
1                            16528.68                            2172.46
2                            19551.90                            1898.30
3                            24171.65                            3670.54
4                            25270.26                            2775.80

   Yield (Quintal/ Hectare)
0                       9.83
1                       7.47
2                       9.59
3                       6.42
4                       8.72
                    State_Name District_Name  Crop_Year       Season  \
0  Andaman and Nicobar Islands      NICOBARS     2000.0  Kharif
1  Andaman and Nicobar Islands      NICOBARS     2000.0  Kharif
2  Andaman and Nicobar Islands      NICOBARS     2000.0  Kharif
3  Andaman and Nicobar Islands      NICOBARS     2000.0  Whole Year
4  Andaman and Nicobar Islands      NICOBARS     2000.0  Whole Year

                  Crop    Area  Production
0             Arecanut  1254.0      2000.0
1  Other Kharif pulses     2.0         1.0
2                 Rice   102.0       321.0
3               Banana   176.0       641.0
4            Cashewnut   720.0       165.0
   temperature   humidity        ph    rainfall label
0    20.879744  82.002744  6.502985  202.935536  rice
1    21.770462  80.319644  7.038096  226.655537  rice
2    23.004459  82.320763  7.840207  263.964248  rice
3    26.491096  80.158363  6.980401  242.864034  rice
4    20.130175  81.604873  7.628473  262.717340  rice
    Rainfall  Temperature   Ph   Crop  Production Cropconversion
0  400.15082         20.0  3.0  Bajra     0.00690          Bajra
1  400.16331         20.0  3.2  Bajra     0.00747          Bajra
2  400.16387         20.0  3.2  Bajra     0.00749          Bajra
3  400.17967         20.0  3.2  Bajra     0.00822          Bajra
4  400.19582         20.0  3.2  Bajra     0.00895          Bajra
           Crop   Ph
0         Bajra  3.0
1        Banana  6.5
2        Barley  3.0
3          Bean  5.5
4  Black pepper  6.4
null values in df1 Crop                                     0
State                                    0
Cost of Cultivation (`/Hectare) A2+FL    0
Cost of Cultivation (`/Hectare) C2       0
Cost of Production (`/Quintal) C2        0
Yield (Quintal/ Hectare)                 0
dtype: int64
null values in df2 State_Name          0
District_Name       1
Crop_Year           1
Season              1
Crop                1
Area                1
Production       1890
dtype: int64
null values in df3 temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64
null values in df4 Rainfall          0
Temperature       0
Ph                0
Crop              0
Production        0
Cropconversion    0
dtype: int64
null values in df5 Crop    0
 Ph     0
dtype: int64

In [ ]:
g=df1
# droping the duplicate values
g.drop_duplicates(subset="State",inplace=True)
print("these crops are the best crops to grow in thes states")
print(g)
df2['Yield']=(df2['Production']/df2['Area'])
o=df2
o.sort_values("Yield",inplace=True,ascending=False)
h=df2
h.drop_duplicates(subset="State_Name",inplace=True)
h.drop(['District_Name','Crop_Year','Season','Area','Production','Yield'],axis=1,inplace=True)
print(h)
k=df4
k.sort_values("Production",inplace=True,ascending=False)
print(k)
j=k
j.drop_duplicates(subset="Crop",inplace=True)
t=j['Production']
j.drop(['Cropconversion','Production'],axis=1,inplace=True)
print("the factors affecting the most are")
print(j)
print('......q2......') 
print("shapes of different dataframes ----->")
print(df1.shape)
print(df2.shape)
print(df3.shape)
print(df4.shape)
print(df5.shape)
df=df4
df.drop('Crop',axis=1,inplace=True)
print(df.isnull().sum())
# dtypes tell about the datatype of each column 
print("datatypes are ----->",df.dtypes)
# for training and testing -> we will split the data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df,t,test_size=0.2)
from sklearn.ensemble import RandomForestRegressor
reg=RandomForestRegressor(max_depth=7,random_state=42,n_estimators=58)
  # fitting the model
reg.fit(x_train,y_train)
  # predicted values
y_pred=reg.predict(x_test)
print("predicted values ---->",y_pred)
print("--------------x------------q3--------------------x---------------------x-")
e=pd.read_csv(r'/content/crop_production (1).csv')
# filling the nan values with mean
# NaN values are generated when arithmetic operations result in undefined or unrepresentable values
e.fillna(e["Production"].mean(),inplace=True)
# it creates a new column named as 'Yield'
e['Yield']=(e['Production']/e['Area'])
o=e
o.sort_values("Yield",inplace=True,ascending=False)
n=o
n.drop_duplicates(subset="District_Name",inplace=True)
# unwanted features
n.drop(['State_Name','Crop_Year','Season','Area','Production','Yield'],axis=1,inplace=True)
print("ðŸ‘Ž")
i=input("enter district name -->")

these crops are the best crops to grow in thes states
         Crop           State  Cost of Cultivation (`/Hectare) A2+FL  \
0       ARHAR   Uttar Pradesh                                9794.05
1       ARHAR       Karnataka                               10593.15
2       ARHAR         Gujarat                               13468.82
3       ARHAR  Andhra Pradesh                               17051.66
4       ARHAR     Maharashtra                               17130.55
6      COTTON          Punjab                               29047.10
9      COTTON         Haryana                               29918.97
10       GRAM       Rajasthan                                8552.69
11       GRAM  Madhya Pradesh                                9803.89
17  GROUNDNUT      Tamil Nadu                               22507.86
20      MAIZE           Bihar                               13513.92
25      MOONG          Orissa                                5483.54
32      PADDY     West Bengal                               24731.06

    Cost of Cultivation (`/Hectare) C2  Cost of Production (`/Quintal) C2  \
0                             23076.74                            1941.55
1                             16528.68                            2172.46
2                             19551.90                            1898.30
3                             24171.65                            3670.54
4                             25270.26                            2775.80
6                             50828.83                            2003.76
9                             44018.18                            2127.35
10                            12610.85                            1691.66
11                            16873.17                            1551.94
17                            30393.66                            2358.00
20                            19857.70                             404.43
25                             8266.98                            2614.14
32                            33046.12                             731.25

    Yield (Quintal/ Hectare)
0                        9.83
1                        7.47
2                        9.59
3                        6.42
4                        8.72
6                       24.39
9                       19.90
10                       6.83
11                      10.29
17                      11.98
20                      42.95
25                       3.01
32                      39.04
                        State_Name       Crop
9829                Andhra Pradesh   Coconut
20171                        Assam   Coconut
57092                          Goa   Coconut
77     Andaman and Nicobar Islands   Coconut
68479                      Haryana      Onion
30471                        Bihar  Sugarcane
56690       Dadra and Nagar Haveli   Coconut
62186                      Gujarat    Sesamum
79887                    Karnataka  Sugarcane
46810                 Chhattisgarh     Banana
75636                    Jharkhand     Potato
10451            Arunachal Pradesh  Sugarcane
74167           Jammu and Kashmir      Potato
45938                   Chandigarh      Onion
72757             Himachal Pradesh     Potato
          Rainfall  Temperature   Ph               Crop  Production  \
103473   715.00000       25.000  7.1              Onion   204.07895
104105  2140.00000       25.800  6.6             Papaya   134.14264
104104  2145.00000       25.850  6.5             Papaya   131.30065
104103  2150.00000       25.900  6.4             Papaya   130.50000
104102  2155.00000       25.950  6.3             Papaya   130.50000
...            ...          ...  ...                ...         ...
57458    400.05866       18.000  6.0              Jowar     0.00117
52622    100.01130       25.010  5.0          Guar seed     0.00113
86452    600.06506       21.005  6.3  Moong(Green Gram)     0.00081
86451    600.04113       21.000  6.3  Moong(Green Gram)     0.00051
52621    100.00340       25.000  5.0          Guar seed     0.00034

           Cropconversion
103473              Onion
104105             Papaya
104104             Papaya
104103             Papaya
104102             Papaya
...                   ...
57458               Jowar
52622           Guar seed
86452   Moong(Green Gram)
86451   Moong(Green Gram)
52621           Guar seed

[116262 rows x 6 columns]
the factors affecting the most are
          Rainfall  Temperature   Ph                   Crop
103473   715.00000     25.00000  7.1                  Onion
104105  2140.00000     25.80000  6.6                 Papaya
30176    911.00000     27.00000  7.3                 Cotton
8309     626.00000     26.00000  7.2                 Banana
86449    755.00000     26.00000  6.0                  Mesta
44095    740.00000     20.30000  7.5                 Grapes
37011   1634.00000     27.64522  6.3                 Ginger
13661    564.00000     23.00000  6.1                Cabbage
84705    760.00000     29.70634  6.4                  Maize
13591    847.43119     24.00000  6.0                Brinjal
33884    718.00000     22.00600  6.5                 Garlic
65692    515.00000     31.22999  6.5                   Jute
67139   1048.00000     24.00000  6.5            Lady Finger
5221     744.01857     24.00000  5.3                  Bajra
64268    760.00000     26.00000  6.8                  Jowar
108441  2028.40244     21.00000  5.8              Pineapple
13967   1700.86291     30.00000  5.9               Cardamom
108439   534.00000     23.00000  7.0  Peas & beans (Pulses)
23117   1072.40000     24.50000  6.3               Chillies
112242   381.01849     17.94100  5.6                 Potato
115340   709.00000     25.00000  6.5                Raddish
103586   500.00000     20.55000  7.8                 Orange
23129    980.00000     28.00000  6.0              Colocosia
16852    174.22200     22.00000  6.5            Cauliflower
95892    790.00000     31.00000  6.8      Moong(Green Gram)
13980    810.23529     15.00000  6.0                 Carrot
13332    510.00000     25.50000  6.8           Bottle Gourd
52619    645.00000     25.43001  6.1              Groundnut
13230   2468.00000     27.00000  6.2           Black pepper
12343    989.53069     24.00000  5.2                 Barley
26061    916.00000     25.00000  8.5              Coriander
71175    596.00000     21.72063  6.0                Linseed
53838    210.00000     26.01000  6.2              Guar seed
43985    734.00000     24.34386  5.8                   Gram
16839    758.53571     24.00000  6.5            Castor seed
30689    952.00000     31.00000  6.0                 Cowpea
57456    810.29412     26.00000  6.4             Horse-gram
67022    610.00000     20.41400  7.0                Khesari
30747   1260.00000     25.31667  6.5             Drum Stick
12363    440.00000     24.00000  5.5                   Bean
13324    701.89781     26.00000  6.2              Blackgram
96473    620.00000     26.00000  7.8                   Moth
67171    627.27273     17.50000  6.9                 Lentil
116261   746.45646     24.60000  5.4                   Ragi
......q2......
shapes of different dataframes ----->
(13, 6)
(15, 2)
(3100, 5)
(44, 4)
(58, 2)
Rainfall       0
Temperature    0
Ph             0
dtype: int64
datatypes are -----> Rainfall       float64
Temperature    float64
Ph             float64
dtype: object
predicted values ----> [ 8.73491906 17.57635243 79.82764629 79.37112741 97.60095414  7.67241256
 16.72154026  6.93592449 13.16443652]
--------------x------------q3--------------------x---------------------x-
ðŸ‘Ž
enter district name -->jaipur

In [ ]:
#-------------x--------------q4------------x-----------------x-------------x----
print("--------------x------------q4--------------------x---------------------x-")
d=pd.read_csv(r'/content/state_wise_crop_production.csv')
# new column as Cost 
d['Cost']=(d['Cost of Cultivation (`/Hectare) A2+FL']+d['Cost of Cultivation (`/Hectare) C2']+d['Cost of Production (`/Quintal) C2'])
# dropping the unwanted features
d.drop(['Cost of Cultivation (`/Hectare) A2+FL','Cost of Cultivation (`/Hectare) C2','Cost of Production (`/Quintal) C2'],axis=1,inplace=True)
d.drop_duplicates(subset="State",inplace=True)
print(d)
i=input("enter state from the above table -->")
# using try and except - for q5 
try:
    # it will tell about that whether it has any true value or not
    t=(d['State']==i).any()
    # if true then it will be executed 
    if t:
       f=d[d['State']==i]
       print("suitable crop for ",i,"with index is",f['Crop'])
    else:
        # it will lead the control flow to the except block
        raise exception
except:
    print("entered state is not in the dataset")

print('q5')
print("solution of ques 5 is done in above quetions ,if there is not a feature matching with the dataset values ,then it will tell the user about it.")

--------------x------------q4--------------------x---------------------x-
         Crop           State  Yield (Quintal/ Hectare)       Cost
0       ARHAR   Uttar Pradesh                       9.83  34812.34
1       ARHAR       Karnataka                       7.47  29294.29
2       ARHAR         Gujarat                       9.59  34919.02
3       ARHAR  Andhra Pradesh                       6.42  44893.85
4       ARHAR     Maharashtra                       8.72  45176.61
6      COTTON          Punjab                      24.39  81879.69
9      COTTON         Haryana                      19.90  76064.50
10       GRAM       Rajasthan                       6.83  22855.20
11       GRAM  Madhya Pradesh                      10.29  28229.00
17  GROUNDNUT      Tamil Nadu                      11.98  55259.52
20      MAIZE           Bihar                      42.95  33776.05
25      MOONG          Orissa                       3.01  16364.66
32      PADDY     West Bengal                      39.04  58508.43
enter state from the above table -->Rajasthan
suitable crop for  Rajasthan with index is 10    GRAM
Name: Crop, dtype: object
q5
solution of ques 5 is done in above quetions ,if there is not a feature matching with the dataset values ,then it will tell the user about it.

In [ ]:
# using try and except - for q5 
try:
     # it will tell about that whether it has any true value or not
    t=(n['District_Name']==i).any()
     # if true then it will be executed 
    if t:
      h=n[n['District_Name']==i]
      print("Crop for district ",i," with index is",h['Crop'])
    else:
        # it will lead the control flow to the except block
        raise Exception
except:
    print("entered district is not in the dataset")

entered district is not in the dataset

In [ ]:
print('q6')
l=pd.read_csv(r'/content/cropproductiononvariousfactors.csv')
l.sort_values("Production",inplace=True,ascending=False)
l.sort_values("Rainfall",inplace=True,ascending=True)
l.drop_duplicates(subset="Crop",inplace=True)
l.drop(['Rainfall','Temperature','Ph'],axis=1,inplace=True)
print("crops which are being grown by farmers ,producion and crop conversion are -->",l)
print("q7")
x=pd.read_csv(r'/content/cropproductiononvariousfactors.csv')
x.sort_values("Production",inplace=True,ascending=False)
x.drop_duplicates(subset="Crop",inplace=True)
x.drop(['Rainfall','Temperature','Production'],axis=1,inplace=True)
print("ph of the soil should be this which is given in the following dataset,for prescribed crops-->",x)
print('q8')
l=pd.read_csv(r'/content/cropproductiononvariousfactors.csv')
p=l
p.sort_values("Production",inplace=True,ascending=False)
print(p)
m=p
m.drop_duplicates(subset="Crop",inplace=True)
d=m['Production']
q=l
q.drop(['Crop','Cropconversion'],axis=1,inplace=True)
print(q)
print("linear regression")
from sklearn.linear_model import LinearRegression
x_train,x_test,y_train,y_test=train_test_split(q,d,test_size=0.2,random_state=100)
reg=LinearRegression()
reg.fit(x_train,y_train)
print("score of linear regression in this project",(reg.score(x_test,y_test))*100)

q6
crops which are being grown by farmers ,producion and crop conversion are -->                          Crop  Production         Cropconversion
52621               Guar seed     0.00034              Guar seed
16841             Cauliflower     8.58333            Cauliflower
64270                    Jute     0.27405                   Jute
108442                 Potato     0.03019                 Potato
104107  Peas & beans (Pulses)     0.04762  Peas & beans (Pulses)
12353                    Bean     1.33333                   Bean
13593                 Cabbage    10.00556                Cabbage
57458                   Jowar     0.00117                  Jowar
67023                 Khesari     0.00179                Khesari
0                       Bajra     0.00690                  Bajra
135467               Sannhamp     0.01011               Sannhamp
156680              Sunflower     0.05000              Sunflower
167645                 Tomato     1.15333                 Tomato
103475                 Orange     1.33333                 Orange
13326            Bottle Gourd     7.00000           Bottle Gourd
71176                 Linseed     0.01143                Linseed
95894                    Moth     0.00351                   Moth
145818               Soyabean     0.06857               Soyabean
5223                   Banana     0.29204                 Banana
96507                   Onion     0.02970                  Onion
71177                   Maize     0.00128                  Maize
137418                Sesamum     0.00123                Sesamum
26063                  Cotton     0.03846                 Cotton
53839              Horse-gram     0.00602             Horse-gram
30749                  Garlic     0.08772                 Garlic
44097               Groundnut     0.02326              Groundnut
13982             Castor seed     0.02000            Castor seed
115323                Raddish     1.51316                Raddish
67141                  Lentil     0.30904                 Lentil
86451       Moong(Green Gram)     0.00051      Moong(Green Gram)
37013                    Gram     0.01637                   Gram
171975                   Urad     0.00943                   Urad
84707                   Mesta     0.13846                  Mesta
181395                  Wheat     0.04626                  Wheat
134270              Safflower     0.03583              Safflower
16856                Chillies     0.02020               Chillies
13334                 Brinjal     2.88123                Brinjal
43987                  Grapes     0.20000                 Grapes
13232               Blackgram     0.39906              Blackgram
115341                   Ragi     0.01270                   Ragi
30178                  Cowpea     0.06143                 Cowpea
166064                Tapioca     0.66667                Tapioca
161962           Sweet potato     0.05000           Sweet potato
23130               Coriander     0.04762              Coriander
30691              Drum Stick     0.01455             Drum Stick
13969                  Carrot     7.00000                 Carrot
8311                   Barley     0.08772                 Barley
67024             Lady Finger     0.33333            Lady Finger
23121               Colocosia     9.50000              Colocosia
148907              Sugarcane     0.10950              Sugarcane
119207                   Rice     0.00389                   Rice
33887                  Ginger     0.10526                 Ginger
103699                 Papaya     0.16244                 Papaya
13663                Cardamom    12.00000               Cardamom
167920               Turmeric     0.19847               Turmeric
181344                 Varagu     0.33127                 Varagu
12365            Black pepper     0.04885           Black pepper
108441              Pineapple    14.20122              Pineapple
q7
ph of the soil should be this which is given in the following dataset,for prescribed crops-->          Ph                   Crop         Cropconversion
156677  7.5              Sugarcane              Sugarcane
103473  7.1                  Onion                  Onion
104105  6.6                 Papaya                 Papaya
30176   7.3                 Cotton                 Cotton
8309    7.2                 Banana                 Banana
167642  6.1                Tapioca                Tapioca
86449   6.0                  Mesta                  Mesta
137416  6.5               Sannhamp               Sannhamp
167917  6.2                 Tomato                 Tomato
44095   7.5                 Grapes                 Grapes
37011   6.3                 Ginger                 Ginger
166061  6.1           Sweet potato           Sweet potato
13661   6.1                Cabbage                Cabbage
84705   6.4                  Maize                  Maize
171972  6.6               Turmeric               Turmeric
13591   6.0                Brinjal                Brinjal
33884   6.5                 Garlic                 Garlic
65692   6.5                   Jute                   Jute
67139   6.5            Lady Finger            Lady Finger
5221    5.3                  Bajra                  Bajra
134268  7.4                   Rice                   Rice
161959  6.3              Sunflower              Sunflower
64268   6.8                  Jowar                  Jowar
108441  5.8              Pineapple              Pineapple
13967   5.9               Cardamom               Cardamom
108439  7.0  Peas & beans (Pulses)  Peas & beans (Pulses)
23117   6.3               Chillies               Chillies
148904  6.6               Soyabean               Soyabean
112242  5.6                 Potato                 Potato
188378  5.8                  Wheat                  Wheat
115340  6.5                Raddish                Raddish
181341  6.6                   Urad                   Urad
103584  7.8                 Orange                 Orange
119205  6.0                   Ragi                   Ragi
23129   6.0              Colocosia              Colocosia
16855   6.5            Cauliflower            Cauliflower
95892   6.8      Moong(Green Gram)      Moong(Green Gram)
13980   6.0                 Carrot                 Carrot
13332   6.8           Bottle Gourd           Bottle Gourd
145816  6.5                Sesamum                Sesamum
52619   6.1              Groundnut              Groundnut
13230   6.2           Black pepper           Black pepper
12343   5.2                 Barley                 Barley
26061   8.5              Coriander              Coriander
71175   6.0                Linseed                Linseed
53838   6.2              Guar seed              Guar seed
43985   5.8                   Gram                   Gram
16839   6.5            Castor seed            Castor seed
30689   6.0                 Cowpea                 Cowpea
57456   6.4             Horse-gram             Horse-gram
135465  6.3              Safflower              Safflower
67022   7.0                Khesari                Khesari
30747   6.5             Drum Stick             Drum Stick
181392  5.9                 Varagu                 Varagu
12363   5.5                   Bean                   Bean
13324   6.2              Blackgram              Blackgram
96498   7.5                   Moth                   Moth
67171   6.9                 Lentil                 Lentil
q8
          Rainfall  Temperature   Ph               Crop  Production  \
156677  1330.00000       31.000  7.5          Sugarcane   955.75034
156676  1320.00000       31.000  7.5          Sugarcane   907.89016
156675  1310.00000       31.000  7.5          Sugarcane   865.32060
156674  1300.00000       31.000  7.5          Sugarcane   842.22092
156673  1290.00000       31.000  7.5          Sugarcane   821.44347
...            ...          ...  ...                ...         ...
57458    400.05866       18.000  6.0              Jowar     0.00117
52622    100.01130       25.010  5.0          Guar seed     0.00113
86452    600.06506       21.005  6.3  Moong(Green Gram)     0.00081
86451    600.04113       21.000  6.3  Moong(Green Gram)     0.00051
52621    100.00340       25.000  5.0          Guar seed     0.00034

           Cropconversion
156677          Sugarcane
156676          Sugarcane
156675          Sugarcane
156674          Sugarcane
156673          Sugarcane
...                   ...
57458               Jowar
52622           Guar seed
86452   Moong(Green Gram)
86451   Moong(Green Gram)
52621           Guar seed

[189232 rows x 6 columns]
          Rainfall  Temperature   Ph  Production
156677  1330.00000     31.00000  7.5   955.75034
103473   715.00000     25.00000  7.1   204.07895
104105  2140.00000     25.80000  6.6   134.14264
30176    911.00000     27.00000  7.3   100.57670
8309     626.00000     26.00000  7.2    88.00000
167642  1157.09700     30.00000  6.1    70.51609
86449    755.00000     26.00000  6.0    68.00000
137416   810.00000     23.00000  6.5    55.55000
167917   515.00000     20.00000  6.2    50.20508
44095    740.00000     20.30000  7.5    42.92783
37011   1634.00000     27.64522  6.3    39.06545
166061  1224.00000     25.00000  6.1    38.12500
13661    564.00000     23.00000  6.1    29.09317
84705    760.00000     29.70634  6.4    25.67709
171972  1730.00000     24.00000  6.6    25.00000
13591    847.43119     24.00000  6.0    24.74312
33884    718.00000     22.00600  6.5    23.63636
65692    515.00000     31.22999  6.5    22.76362
67139   1048.00000     24.00000  6.5    19.45188
5221     744.01857     24.00000  5.3    15.73016
134268  1480.00000     24.00000  7.4    15.19048
161959   620.00000     25.00000  6.3    14.68966
64268    760.00000     26.00000  6.8    14.56875
108441  2028.40244     21.00000  5.8    14.20122
13967   1700.86291     30.00000  5.9    14.14700
108439   534.00000     23.00000  7.0    13.58919
23117   1072.40000     24.50000  6.3    13.00000
148904   565.00000     25.00000  6.6    11.44444
112242   381.01849     17.94100  5.6    10.83092
188378   706.68875     29.00000  5.8    10.46320
115340   709.00000     25.00000  6.5    10.33333
181341   830.00000     32.00000  6.6    10.00000
103584   500.00000     20.45000  7.8    10.00000
119205  1010.00000     25.00000  6.0     9.75000
23129    980.00000     28.00000  6.0     9.52273
16855    160.20000     22.00000  6.5     9.00000
95892    790.00000     31.00000  6.8     8.00000
13980    810.23529     15.00000  6.0     7.52941
13332    510.00000     25.50000  6.8     7.25000
145816   700.00000     23.00000  6.5     6.25000
52619    645.00000     25.43001  6.1     6.14588
13230   2468.00000     27.00000  6.2     6.00000
12343    989.53069     24.00000  5.2     5.41516
26061    916.00000     25.00000  8.5     5.37500
71175    596.00000     21.72063  6.0     5.09091
53838    210.00000     26.01000  6.2     5.03136
43985    734.00000     24.34386  5.8     4.80769
16839    758.53571     24.00000  6.5     3.73438
30689    952.00000     31.00000  6.0     3.25000
57456    810.29412     26.00000  6.4     3.10294
135465   800.00000     24.00000  6.3     2.80000
67022    610.00000     20.41400  7.0     2.61023
30747   1260.00000     25.31667  6.5     2.05211
181392  1615.22700     28.00000  5.9     1.92045
12363    440.00000     24.00000  5.5     1.40000
13324    701.89781     26.00000  6.2     1.01898
96498    620.00000     27.00000  7.5     1.00000
67171    627.27273     17.50000  6.9     0.84848
linear regression
score of linear regression in this project 100.0